"""Add customer_phone to claims table

Revision ID: 090373bacc47
Revises: 1a23e4055458
Create Date: 2025-11-08 08:37:17.650853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090373bacc47'
down_revision: Union[str, Sequence[str], None] = '1a23e4055458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('customer_phone', sa.String(), nullable=True))
    op.drop_index(op.f('claims_search_vector_idx'), table_name='claims', postgresql_using='gin')
    op.create_index(op.f('ix_claims_customer_phone'), 'claims', ['customer_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_customer_phone'), table_name='claims')
    op.create_index(op.f('claims_search_vector_idx'), 'claims', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('claims', 'customer_phone')
    # ### end Alembic commands ###
