"""New migration

Revision ID: 1a23e4055458
Revises: 38cc799f661e
Create Date: 2025-11-08 01:29:13.358733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a23e4055458'
down_revision: Union[str, Sequence[str], None] = '38cc799f661e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('date_reported', sa.DateTime(), nullable=True),
    sa.Column('incident_date', sa.DateTime(), nullable=False),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('policy_type', sa.Enum('AUTO', 'HOME', 'MEDICAL', 'THEFT', name='policytype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'PAID', 'DENIED', 'CLOSED', name='claimstatus'), nullable=False),
    sa.Column('estimated_damage', sa.Float(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('assigned_adjuster', sa.String(), nullable=True),
    sa.Column('agent_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_customer_id'), 'claims', ['customer_id'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_incident_type'), 'claims', ['incident_type'], unique=False)
    op.create_index(op.f('ix_claims_policy_id'), 'claims', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_policy_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_incident_type'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_customer_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
